

import global_vars




sys.excepthook = handle_exception
